on:
  push:
    paths:
      - "xmake.lua"
      - "src/**/*"
      - "tests/**/*"
      - "include/**/*"
      - ".github/workflows/test.yml"
  pull_request:
    paths:
      - "xmake.lua"
      - "src/**/*"
      - "tests/**/*"
      - "include/**/*"
      - ".github/workflows/test.yml"
  workflow_dispatch:

jobs:
  build:
    name: "Uint Test"
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: xmake-io/github-action-setup-xmake@v1
        # with:
        #   xmake-version: branch@master

      - uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-

      - run: |
          xmake repo -u

      - run: |
          xmake f -v -y -m release -p windows -a x64 --test=y

      - run: |
          xmake -v -y

      - name: Run tests
        run: |
          ./bin/qjspp.exe
